import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Crete_Round as FontRound } from "next/font/google";
import { Manrope as FontManrope } from "next/font/google";
import { Rubik as FontRubik } from "next/font/google";
import "./globals.css";
import { cn } from "@/src/lib/utils";
import { AppWrapper } from "@/src/context";
import { ThemeProvider } from "@/src/components/theme-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontRound = FontRound({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-round",
});
const fontManrope = FontManrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});
const fontRubik = FontRubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "MoneyMystery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-manrope antialiased",
          fontSans.variable,
          fontRound.variable,
          fontManrope.variable,
          fontRubik.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AppWrapper>{children}</AppWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
